[package]
name = "vaultify"
version = "0.1.0"
authors = ["Alex Zepeda <alex@inferiorhumanorgans.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
serde = "1.0"
serde_json = "1.0"
shell-escape = "0.1.3"
clap = "~2.26.0"
hyper-tls = "0.1.2"
